apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - atlas.sagesure.io
      secretName: atlas-tls
  rules:
    - host: atlas.sagesure.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: atlas-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlas-shell
                port:
                  number: 80
